from __future__ import annotations

import json
from pathlib import Path


def markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def build_notebook() -> dict:
    cells: list[dict] = [
        markdown_cell(
            "# Experiment: SpectralBio Block 3 - Structure Bridge (H100)\n\n"
            "Objective:\n"
            "- Connect the Block 2 repair regime to local structural context without burning compute on full mutant folding.\n"
            "- Reuse the strongest failure-mode exemplars, fetch WT AlphaFold structures with cache, and quantify pLDDT plus local contact density.\n"
            "- Produce a reviewer-facing bridge from covariance repair to local structural tension, while degrading honestly if the bridge is weak.\n"
            "- Save a complete Lightning-friendly bundle under `New Notebooks/results/05_block3_structure_bridge_h100/`.\n"
        ),
        markdown_cell(
            "## Block 3 Deliverables\n\n"
            "- A cached WT-structure panel for Block 2 repair exemplars, matched controls, and likelihood-driven reference variants.\n"
            "- Local structure metrics around each mutation: residue-resolution, window pLDDT, contact density, and long-range contact fraction.\n"
            "- Correlation and cohort summaries tying `pair_repair` / `frob_repair` to structure-aware signals.\n"
            "- Reviewer-friendly figures showing whether covariance-heavy cases concentrate in more contact-dense or more structurally confident neighborhoods.\n"
            "- A `block5_summary.json` and `block5_summary.md` claim that stays honest if the result is only suggestive.\n\n"
            "## Runtime contract\n\n"
            "- Target environment: **Lightning AI Studio**\n"
            "- Target hardware: **H100**\n"
            "- The notebook is intentionally compute-safe: no full-panel ESMFold reruns, no mutant structure prediction requirement.\n"
            "- All outputs are written under `New Notebooks/results/05_block3_structure_bridge_h100/`.\n"
        ),
        code_cell(
            "# Setup: imports, identifiers, and notebook knobs\n"
            "from __future__ import annotations\n\n"
            "import importlib\n"
            "import io\n"
            "import json\n"
            "import math\n"
            "import os\n"
            "import platform\n"
            "import shutil\n"
            "import subprocess\n"
            "import sys\n"
            "import zipfile\n"
            "from datetime import datetime, timezone\n"
            "from pathlib import Path\n\n"
            "import matplotlib.pyplot as plt\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "from IPython.display import display\n\n"
            "NOTEBOOK_SLUG = '05_block3_structure_bridge_h100'\n"
            "ACCOUNT_LABEL = os.environ.get('SPECTRALBIO_ACCOUNT_LABEL', 'SET_ACCOUNT_LABEL_HERE')\n"
            "RUN_AT = datetime.now(timezone.utc).isoformat()\n"
            "SEED = int(os.environ.get('SPECTRALBIO_RANDOM_SEED', '42'))\n"
            "WINDOW_RADIUS = int(os.environ.get('SPECTRALBIO_BLOCK5_WINDOW_RADIUS', '20'))\n"
            "CONTACT_RADIUS_ANGSTROM = float(os.environ.get('SPECTRALBIO_BLOCK5_CONTACT_RADIUS', '8.0'))\n"
            "LONG_RANGE_GAP = int(os.environ.get('SPECTRALBIO_BLOCK5_LONG_RANGE_GAP', '24'))\n"
            "TOP_CASES = int(os.environ.get('SPECTRALBIO_BLOCK5_TOP_CASES', '3'))\n"
            "OVERWRITE = os.environ.get('SPECTRALBIO_OVERWRITE', '').strip().lower() in {'1', 'true', 'yes'}\n\n"
            "def done(message: str) -> None:\n"
            "    print(f'TERMINEI PODE SEGUIR - {message}')\n\n"
            "print({\n"
            "    'notebook_slug': NOTEBOOK_SLUG,\n"
            "    'account_label': ACCOUNT_LABEL,\n"
            "    'seed': SEED,\n"
            "    'window_radius': WINDOW_RADIUS,\n"
            "    'contact_radius_angstrom': CONTACT_RADIUS_ANGSTROM,\n"
            "    'long_range_gap': LONG_RANGE_GAP,\n"
            "    'top_cases': TOP_CASES,\n"
            "    'overwrite': OVERWRITE,\n"
            "    'python': sys.version.split()[0],\n"
            "    'platform': platform.platform(),\n"
            "})\n"
            "done('Initial configuration loaded.')\n"
        ),
        code_cell(
            "# Helpers: subprocess, repo discovery, path resolution, and utility functions\n"
            "def run(command: list[str], cwd: Path | None = None, check: bool = True) -> str:\n"
            "    completed = subprocess.run(\n"
            "        command,\n"
            "        cwd=str(cwd) if cwd is not None else None,\n"
            "        check=check,\n"
            "        text=True,\n"
            "        encoding='utf-8',\n"
            "        errors='replace',\n"
            "        capture_output=True,\n"
            "    )\n"
            "    if completed.stdout.strip():\n"
            "        print(completed.stdout.strip())\n"
            "    if completed.stderr.strip():\n"
            "        print(completed.stderr.strip())\n"
            "    return completed.stdout\n\n"
            "def ensure_dir(path: Path) -> Path:\n"
            "    path.mkdir(parents=True, exist_ok=True)\n"
            "    return path\n\n"
            "def looks_like_repo(path: Path) -> bool:\n"
            "    return (path / 'src' / 'spectralbio').exists() and (path / 'notebooks').exists()\n\n"
            "def find_repo_root() -> Path:\n"
            "    env_repo = os.environ.get('SPECTRALBIO_REPO_ROOT', '').strip()\n"
            "    candidates: list[Path] = []\n"
            "    if env_repo:\n"
            "        candidates.append(Path(env_repo).expanduser())\n"
            "    cwd = Path.cwd().resolve()\n"
            "    candidates.extend([\n"
            "        cwd,\n"
            "        cwd.parent,\n"
            "        Path('/teamspace/studios/this_studio/Stanford-Claw4s'),\n"
            "        Path('/teamspace/studios/this_studio/SpectralBio'),\n"
            "        Path('/content/Stanford-Claw4s'),\n"
            "    ])\n"
            "    for candidate in candidates:\n"
            "        if looks_like_repo(candidate):\n"
            "            return candidate.resolve()\n"
            "    raise FileNotFoundError('Could not locate the SpectralBio repository root. Set SPECTRALBIO_REPO_ROOT or run inside the repo.')\n\n"
            "def resolve_existing_path(raw: str | Path, repo_root: Path) -> Path:\n"
            "    raw_path = Path(raw)\n"
            "    if raw_path.exists():\n"
            "        return raw_path.resolve()\n"
            "    raw_text = str(raw).replace('\\\\', '/')\n"
            "    for prefix in ('/content/Stanford-Claw4s/', '/teamspace/studios/this_studio/Stanford-Claw4s/', '/teamspace/studios/this_studio/SpectralBio/'):\n"
            "        if raw_text.startswith(prefix):\n"
            "            candidate = repo_root / raw_text[len(prefix):]\n"
            "            if candidate.exists():\n"
            "                return candidate.resolve()\n"
            "    if 'Stanford-Claw4s/' in raw_text:\n"
            "        candidate = repo_root / raw_text.split('Stanford-Claw4s/', 1)[1]\n"
            "        if candidate.exists():\n"
            "            return candidate.resolve()\n"
            "    if not raw_path.is_absolute():\n"
            "        candidate = (repo_root / raw_path).resolve()\n"
            "        if candidate.exists():\n"
            "            return candidate\n"
            "    return raw_path\n\n"
            "def safe_float(value, default: float = float('nan')) -> float:\n"
            "    try:\n"
            "        return float(value)\n"
            "    except Exception:\n"
            "        return default\n\n"
            "def median_or_nan(series: pd.Series) -> float:\n"
            "    values = pd.to_numeric(series, errors='coerce').dropna()\n"
            "    if values.empty:\n"
            "        return float('nan')\n"
            "    return float(values.median())\n\n"
            "def spearman_or_nan(left: pd.Series, right: pd.Series) -> float:\n"
            "    frame = pd.DataFrame({'left': pd.to_numeric(left, errors='coerce'), 'right': pd.to_numeric(right, errors='coerce')}).dropna()\n"
            "    if len(frame) < 3:\n"
            "        return float('nan')\n"
            "    return float(frame['left'].corr(frame['right'], method='spearman'))\n\n"
            "done('Helpers ready.')\n"
        ),
        code_cell(
            "# Resolve repository root, outputs, and runtime dependencies\n"
            "REPO_ROOT = find_repo_root()\n"
            "RESULTS_ROOT = ensure_dir(REPO_ROOT / 'New Notebooks' / 'results' / NOTEBOOK_SLUG)\n"
            "TABLES_DIR = ensure_dir(RESULTS_ROOT / 'tables')\n"
            "FIGURES_DIR = ensure_dir(RESULTS_ROOT / 'figures')\n"
            "TEXT_DIR = ensure_dir(RESULTS_ROOT / 'text')\n"
            "MANIFESTS_DIR = ensure_dir(RESULTS_ROOT / 'manifests')\n"
            "RUNTIME_DIR = ensure_dir(RESULTS_ROOT / 'runtime')\n"
            "STRUCTURE_CACHE_DIR = ensure_dir(RUNTIME_DIR / 'structure_cache')\n"
            "ZIP_PATH = REPO_ROOT / 'New Notebooks' / 'results' / f'{NOTEBOOK_SLUG}.zip'\n"
            "ROOT_ZIP_COPY = REPO_ROOT / 'New Notebooks' / f'{NOTEBOOK_SLUG}.zip'\n\n"
            "RUNTIME_REQUIREMENTS = [\n"
            "    ('numpy', 'numpy==2.1.3'),\n"
            "    ('pandas', 'pandas==2.2.3'),\n"
            "    ('matplotlib', 'matplotlib==3.9.2'),\n"
            "    ('requests', 'requests==2.32.3'),\n"
            "]\n"
            "missing = []\n"
            "for module_name, package_name in RUNTIME_REQUIREMENTS:\n"
            "    try:\n"
            "        importlib.import_module(module_name)\n"
            "    except Exception:\n"
            "        missing.append(package_name)\n"
            "if missing:\n"
            "    run([sys.executable, '-m', 'pip', 'install', *missing], cwd=REPO_ROOT)\n"
            "    importlib.invalidate_caches()\n"
            "import requests\n\n"
            "repo_status = {\n"
            "    'repo_root': str(REPO_ROOT),\n"
            "    'head_commit': run(['git', 'rev-parse', 'HEAD'], cwd=REPO_ROOT).strip(),\n"
            "    'head_subject': run(['git', 'log', '-1', '--pretty=%s'], cwd=REPO_ROOT).strip(),\n"
            "    'branch': run(['git', 'branch', '--show-current'], cwd=REPO_ROOT).strip(),\n"
            "}\n"
            "display(pd.DataFrame([repo_status]))\n"
            "done('Repository, output directories, and dependencies confirmed.')\n"
        ),
        code_cell(
            "# Load frozen Block 2 evidence and choose the structure cohorts\n"
            "annotated_path = resolve_existing_path('New Notebooks/results/02_block2_failure_mode_hunt_h100/tables/annotated_failure_mode_rows.csv', REPO_ROOT)\n"
            "exemplars_path = resolve_existing_path('New Notebooks/results/02_block2_failure_mode_hunt_h100/tables/candidate_exemplars_ranked.csv', REPO_ROOT)\n"
            "context_path = resolve_existing_path('New Notebooks/results/02_block2_failure_mode_hunt_h100/tables/context_enrichment_summary.csv', REPO_ROOT)\n"
            "block4_anchor_path = resolve_existing_path('New Notebooks/results/03_block4_model_agnostic_plms_h100_v2/tables/model_agnostic_anchor_long.csv', REPO_ROOT)\n\n"
            "annotated = pd.read_csv(annotated_path)\n"
            "exemplars = pd.read_csv(exemplars_path)\n"
            "context_summary = pd.read_csv(context_path)\n"
            "block4_anchor = pd.read_csv(block4_anchor_path) if block4_anchor_path.exists() else pd.DataFrame()\n\n"
            "annotated['alphafold_prediction_available'] = annotated['alphafold_prediction_available'].fillna(0).astype(int)\n"
            "exemplars = exemplars.sort_values(['pair_repair', 'frob_repair'], ascending=False).copy()\n"
            "repair_exemplars = exemplars[(exemplars['is_repair_exemplar'] == True)].copy()\n"
            "repair_exemplars = repair_exemplars[repair_exemplars['uniprot_accession'].notna()] if 'uniprot_accession' in repair_exemplars.columns else repair_exemplars\n"
            "if 'uniprot_accession' not in repair_exemplars.columns:\n"
            "    repair_exemplars = repair_exemplars.merge(\n"
            "        annotated[['variant_id', 'uniprot_accession', 'alphafold_prediction_available']].drop_duplicates(),\n"
            "        on='variant_id',\n"
            "        how='left',\n"
            "    )\n"
            "repair_exemplars = repair_exemplars[repair_exemplars['alphafold_prediction_available'].fillna(0).astype(int) == 1].copy()\n\n"
            "controls = annotated[(annotated['is_control'] == True) & (annotated['alphafold_prediction_available'] == 1)].copy()\n"
            "matched_rows = []\n"
            "for row in repair_exemplars.to_dict(orient='records'):\n"
            "    gene_controls = controls[controls['gene'] == row['gene']].copy()\n"
            "    if gene_controls.empty:\n"
            "        continue\n"
            "    gene_controls['distance_to_exemplar'] = (gene_controls['position'] - row['position']).abs()\n"
            "    best = gene_controls.sort_values(['distance_to_exemplar', 'll_norm'], ascending=[True, False]).iloc[0].to_dict()\n"
            "    best['matched_variant_id'] = row['variant_id']\n"
            "    matched_rows.append(best)\n"
            "matched_controls = pd.DataFrame(matched_rows).drop_duplicates(subset=['variant_id']).copy()\n\n"
            "likelihood_refs = annotated[\n"
            "    (annotated['alphafold_prediction_available'] == 1)\n"
            "    & (~annotated['variant_id'].isin(repair_exemplars['variant_id']))\n"
            "    & (~annotated['variant_id'].isin(matched_controls['variant_id']) if not matched_controls.empty else True)\n"
            "].copy()\n"
            "likelihood_refs = likelihood_refs.sort_values(['ll_norm', 'frob_norm'], ascending=[False, True]).head(max(TOP_CASES + 2, 5)).copy()\n\n"
            "repair_exemplars['cohort'] = 'repair_exemplar'\n"
            "matched_controls['cohort'] = 'matched_control'\n"
            "likelihood_refs['cohort'] = 'likelihood_reference'\n"
            "selected_variants = pd.concat([repair_exemplars, matched_controls, likelihood_refs], ignore_index=True, sort=False)\n"
            "selected_variants = selected_variants.drop_duplicates(subset=['variant_id']).reset_index(drop=True)\n"
            "selected_variants.to_csv(TABLES_DIR / 'selected_structure_bridge_variants.csv', index=False)\n"
            "display(selected_variants[['cohort', 'gene', 'variant_id', 'position', 'wt_aa', 'mut_aa', 'pair_repair', 'frob_repair', 'll_repair', 'uniprot_accession']])\n"
            "done('Frozen evidence loaded and structure cohorts selected.')\n"
        ),
        code_cell(
            "# AlphaFold helpers, PDB parsing, and local WT-structure metrics\n"
            "THREE_TO_ONE = {\n"
            "    'ALA': 'A', 'ARG': 'R', 'ASN': 'N', 'ASP': 'D', 'CYS': 'C', 'GLN': 'Q', 'GLU': 'E', 'GLY': 'G',\n"
            "    'HIS': 'H', 'ILE': 'I', 'LEU': 'L', 'LYS': 'K', 'MET': 'M', 'PHE': 'F', 'PRO': 'P', 'SER': 'S',\n"
            "    'THR': 'T', 'TRP': 'W', 'TYR': 'Y', 'VAL': 'V',\n"
            "}\n\n"
            "def fetch_alphafold_pdb(accession: str) -> tuple[Path | None, dict]:\n"
            "    accession = accession.strip()\n"
            "    pdb_path = STRUCTURE_CACHE_DIR / f'{accession}.pdb'\n"
            "    meta_path = STRUCTURE_CACHE_DIR / f'{accession}.json'\n"
            "    if pdb_path.exists() and meta_path.exists() and not OVERWRITE:\n"
            "        return pdb_path, json.loads(meta_path.read_text(encoding='utf-8'))\n\n"
            "    metadata: dict = {'accession': accession, 'status': 'missing'}\n"
            "    api_url = f'https://alphafold.ebi.ac.uk/api/prediction/{accession}'\n"
            "    try:\n"
            "        response = requests.get(api_url, timeout=30)\n"
            "        if response.ok:\n"
            "            payload = response.json()\n"
            "            if isinstance(payload, list) and payload:\n"
            "                metadata.update(payload[0])\n"
            "    except Exception as exc:\n"
            "        metadata['api_error'] = f'{type(exc).__name__}: {exc}'\n\n"
            "    pdb_candidates = []\n"
            "    if metadata.get('pdbUrl'):\n"
            "        pdb_candidates.append(metadata['pdbUrl'])\n"
            "    pdb_candidates.extend([\n"
            "        f'https://alphafold.ebi.ac.uk/files/AF-{accession}-F1-model_v4.pdb',\n"
            "        f'https://alphafold.ebi.ac.uk/files/AF-{accession}-F1-model_v3.pdb',\n"
            "    ])\n\n"
            "    for pdb_url in pdb_candidates:\n"
            "        try:\n"
            "            pdb_response = requests.get(pdb_url, timeout=30)\n"
            "            if pdb_response.ok and 'ATOM' in pdb_response.text:\n"
            "                pdb_path.write_text(pdb_response.text, encoding='utf-8')\n"
            "                metadata['status'] = 'downloaded'\n"
            "                metadata['pdb_url'] = pdb_url\n"
            "                meta_path.write_text(json.dumps(metadata, indent=2), encoding='utf-8')\n"
            "                return pdb_path, metadata\n"
            "        except Exception as exc:\n"
            "            metadata['pdb_error'] = f'{type(exc).__name__}: {exc}'\n\n"
            "    meta_path.write_text(json.dumps(metadata, indent=2), encoding='utf-8')\n"
            "    return None, metadata\n\n"
            "def parse_ca_records(pdb_path: Path) -> pd.DataFrame:\n"
            "    rows = []\n"
            "    for line in pdb_path.read_text(encoding='utf-8', errors='replace').splitlines():\n"
            "        if not line.startswith('ATOM'):\n"
            "            continue\n"
            "        atom_name = line[12:16].strip()\n"
            "        if atom_name != 'CA':\n"
            "            continue\n"
            "        residue_name = line[17:20].strip().upper()\n"
            "        if residue_name not in THREE_TO_ONE:\n"
            "            continue\n"
            "        residue_number = int(line[22:26].strip())\n"
            "        x = float(line[30:38].strip())\n"
            "        y = float(line[38:46].strip())\n"
            "        z = float(line[46:54].strip())\n"
            "        plddt = float(line[60:66].strip())\n"
            "        rows.append({\n"
            "            'residue_number': residue_number,\n"
            "            'aa': THREE_TO_ONE[residue_name],\n"
            "            'x': x,\n"
            "            'y': y,\n"
            "            'z': z,\n"
            "            'plddt': plddt,\n"
            "        })\n"
            "    return pd.DataFrame(rows)\n\n"
            "def resolve_site_row(ca_df: pd.DataFrame, position: int, wt_aa: str) -> pd.Series | None:\n"
            "    for candidate in [position, position + 1, position - 1]:\n"
            "        match = ca_df[(ca_df['residue_number'] == candidate) & (ca_df['aa'] == wt_aa)]\n"
            "        if not match.empty:\n"
            "            return match.iloc[0]\n"
            "    for candidate in [position, position + 1, position - 1]:\n"
            "        match = ca_df[ca_df['residue_number'] == candidate]\n"
            "        if not match.empty:\n"
            "            return match.iloc[0]\n"
            "    return None\n\n"
            "def compute_structure_metrics(ca_df: pd.DataFrame, site_row: pd.Series) -> dict:\n"
            "    coords = ca_df[['x', 'y', 'z']].to_numpy(dtype=float)\n"
            "    residue_numbers = ca_df['residue_number'].to_numpy(dtype=int)\n"
            "    site_index = int(site_row.name)\n"
            "    deltas = coords - coords[site_index]\n"
            "    dists = np.sqrt((deltas ** 2).sum(axis=1))\n"
            "    seq_gap = np.abs(residue_numbers - int(site_row['residue_number']))\n"
            "    contact_mask = (dists <= CONTACT_RADIUS_ANGSTROM) & (seq_gap >= 3)\n"
            "    long_range_mask = (dists <= CONTACT_RADIUS_ANGSTROM) & (seq_gap >= LONG_RANGE_GAP)\n"
            "    window_mask = np.abs(residue_numbers - int(site_row['residue_number'])) <= WINDOW_RADIUS\n"
            "    window_df = ca_df.loc[window_mask].copy()\n"
            "    window_coords = window_df[['x', 'y', 'z']].to_numpy(dtype=float)\n"
            "    if len(window_coords) >= 2:\n"
            "        pairwise = np.sqrt(((window_coords[:, None, :] - window_coords[None, :, :]) ** 2).sum(axis=2))\n"
            "        contact_map = ((pairwise <= CONTACT_RADIUS_ANGSTROM) & (pairwise > 0)).astype(int)\n"
            "    else:\n"
            "        contact_map = np.zeros((len(window_coords), len(window_coords)), dtype=int)\n"
            "    return {\n"
            "        'resolved_residue_number': int(site_row['residue_number']),\n"
            "        'resolved_wt_aa': site_row['aa'],\n"
            "        'site_plddt': float(site_row['plddt']),\n"
            "        'window_plddt_mean': float(window_df['plddt'].mean()) if not window_df.empty else float('nan'),\n"
            "        'window_size_resolved': int(len(window_df)),\n"
            "        'site_contact_count': int(contact_mask.sum() - 1 if contact_mask[site_index] else contact_mask.sum()),\n"
            "        'site_long_range_contact_count': int(long_range_mask.sum()),\n"
            "        'window_contact_mean': float(contact_map.sum(axis=1).mean()) if len(contact_map) else float('nan'),\n"
            "        'window_contact_max': float(contact_map.sum(axis=1).max()) if len(contact_map) else float('nan'),\n"
            "        'window_confident_fraction': float((window_df['plddt'] >= 70).mean()) if not window_df.empty else float('nan'),\n"
            "        'contact_map': contact_map.tolist(),\n"
            "        'window_residue_numbers': window_df['residue_number'].astype(int).tolist(),\n"
            "    }\n\n"
            "done('Structure helpers ready.')\n"
        ),
        code_cell(
            "# Fetch WT structures, compute local metrics, and cache per-accession outputs\n"
            "structure_rows = []\n"
            "cache_rows = []\n"
            "contact_maps: dict[str, dict] = {}\n\n"
            "for row in selected_variants.to_dict(orient='records'):\n"
            "    accession = str(row['uniprot_accession']).strip()\n"
            "    pdb_path, metadata = fetch_alphafold_pdb(accession)\n"
            "    cache_rows.append({\n"
            "        'variant_id': row['variant_id'],\n"
            "        'gene': row['gene'],\n"
            "        'cohort': row['cohort'],\n"
            "        'uniprot_accession': accession,\n"
            "        'pdb_cached': pdb_path is not None,\n"
            "        'structure_status': metadata.get('status', 'missing'),\n"
            "        'pdb_url': metadata.get('pdb_url', ''),\n"
            "        'api_error': metadata.get('api_error', ''),\n"
            "        'pdb_error': metadata.get('pdb_error', ''),\n"
            "    })\n"
            "    if pdb_path is None:\n"
            "        continue\n"
            "    ca_df = parse_ca_records(pdb_path)\n"
            "    if ca_df.empty:\n"
            "        continue\n"
            "    site_row = resolve_site_row(ca_df, int(row['position']), str(row['wt_aa']))\n"
            "    if site_row is None:\n"
            "        continue\n"
            "    metrics = compute_structure_metrics(ca_df, site_row)\n"
            "    contact_maps[row['variant_id']] = {\n"
            "        'contact_map': metrics.pop('contact_map'),\n"
            "        'window_residue_numbers': metrics.pop('window_residue_numbers'),\n"
            "    }\n"
            "    structure_rows.append({**row, **metrics, 'exact_residue_found': int(metrics['resolved_wt_aa'] == str(row['wt_aa']))})\n\n"
            "structure_metrics = pd.DataFrame(structure_rows)\n"
            "cache_manifest = pd.DataFrame(cache_rows)\n"
            "structure_metrics.to_csv(TABLES_DIR / 'structure_bridge_metrics.csv', index=False)\n"
            "cache_manifest.to_csv(TABLES_DIR / 'structure_cache_manifest.csv', index=False)\n"
            "display(cache_manifest)\n"
            "display(structure_metrics[['cohort', 'gene', 'variant_id', 'resolved_residue_number', 'site_plddt', 'window_plddt_mean', 'site_contact_count', 'site_long_range_contact_count', 'window_contact_mean']])\n"
            "done('WT structures cached and local metrics computed.')\n"
        ),
        code_cell(
            "# Build cohort summaries, bridge readouts, and reviewer-facing figures\n"
            "if structure_metrics.empty:\n"
            "    raise RuntimeError('No WT structure metrics could be computed. Stopping before any empty-claim output.')\n\n"
            "cohort_summary = (\n"
            "    structure_metrics\n"
            "    .groupby('cohort', dropna=False)\n"
            "    .agg(\n"
            "        n_variants=('variant_id', 'count'),\n"
            "        median_pair_repair=('pair_repair', median_or_nan),\n"
            "        median_frob_repair=('frob_repair', median_or_nan),\n"
            "        median_ll_repair=('ll_repair', median_or_nan),\n"
            "        median_site_plddt=('site_plddt', median_or_nan),\n"
            "        median_window_plddt=('window_plddt_mean', median_or_nan),\n"
            "        median_site_contacts=('site_contact_count', median_or_nan),\n"
            "        median_long_range_contacts=('site_long_range_contact_count', median_or_nan),\n"
            "        median_window_contact_mean=('window_contact_mean', median_or_nan),\n"
            "        median_window_confident_fraction=('window_confident_fraction', median_or_nan),\n"
            "    )\n"
            "    .reset_index()\n"
            ")\n\n"
            "repair_row = cohort_summary[cohort_summary['cohort'] == 'repair_exemplar']\n"
            "reference_row = cohort_summary[cohort_summary['cohort'] == 'likelihood_reference']\n"
            "repair_window_contact = float(repair_row['median_window_contact_mean'].iloc[0]) if not repair_row.empty else float('nan')\n"
            "reference_window_contact = float(reference_row['median_window_contact_mean'].iloc[0]) if not reference_row.empty else float('nan')\n"
            "repair_window_plddt = float(repair_row['median_window_plddt'].iloc[0]) if not repair_row.empty else float('nan')\n"
            "reference_window_plddt = float(reference_row['median_window_plddt'].iloc[0]) if not reference_row.empty else float('nan')\n\n"
            "core_readout = pd.DataFrame([\n"
            "    {\n"
            "        'metric_name': 'pair_repair_vs_site_contact_count',\n"
            "        'value': spearman_or_nan(structure_metrics['pair_repair'], structure_metrics['site_contact_count']),\n"
            "    },\n"
            "    {\n"
            "        'metric_name': 'pair_repair_vs_window_plddt_mean',\n"
            "        'value': spearman_or_nan(structure_metrics['pair_repair'], structure_metrics['window_plddt_mean']),\n"
            "    },\n"
            "    {\n"
            "        'metric_name': 'frob_repair_vs_site_long_range_contact_count',\n"
            "        'value': spearman_or_nan(structure_metrics['frob_repair'], structure_metrics['site_long_range_contact_count']),\n"
            "    },\n"
            "    {\n"
            "        'metric_name': 'repair_minus_reference_window_contact_median',\n"
            "        'value': repair_window_contact - reference_window_contact if not math.isnan(repair_window_contact) and not math.isnan(reference_window_contact) else float('nan'),\n"
            "    },\n"
            "    {\n"
            "        'metric_name': 'repair_minus_reference_window_plddt_median',\n"
            "        'value': repair_window_plddt - reference_window_plddt if not math.isnan(repair_window_plddt) and not math.isnan(reference_window_plddt) else float('nan'),\n"
            "    },\n"
            "])\n\n"
            "cohort_summary.to_csv(TABLES_DIR / 'structure_bridge_cohort_summary.csv', index=False)\n"
            "core_readout.to_csv(TABLES_DIR / 'structure_bridge_core_readout.csv', index=False)\n\n"
            "def save_scatter(x_col: str, y_col: str, title: str, out_name: str) -> None:\n"
            "    fig, ax = plt.subplots(figsize=(7, 5))\n"
            "    for cohort_name, cohort_df in structure_metrics.groupby('cohort'):\n"
            "        ax.scatter(cohort_df[x_col], cohort_df[y_col], s=70, alpha=0.85, label=cohort_name)\n"
            "    ax.set_xlabel(x_col)\n"
            "    ax.set_ylabel(y_col)\n"
            "    ax.set_title(title)\n"
            "    ax.legend(frameon=False)\n"
            "    ax.grid(alpha=0.25)\n"
            "    fig.tight_layout()\n"
            "    fig.savefig(FIGURES_DIR / out_name, dpi=220)\n"
            "    plt.close(fig)\n\n"
            "save_scatter('site_contact_count', 'pair_repair', 'Pair repair vs local contact count', 'pair_repair_vs_site_contact_count.png')\n"
            "save_scatter('window_plddt_mean', 'pair_repair', 'Pair repair vs window pLDDT', 'pair_repair_vs_window_plddt_mean.png')\n\n"
            "boxplot_columns = ['site_contact_count', 'window_plddt_mean']\n"
            "for column in boxplot_columns:\n"
            "    fig, ax = plt.subplots(figsize=(7, 5))\n"
            "    groups = [group[column].dropna().to_numpy(dtype=float) for _, group in structure_metrics.groupby('cohort')]\n"
            "    labels = [name for name, _ in structure_metrics.groupby('cohort')]\n"
            "    ax.boxplot(groups, tick_labels=labels, showfliers=False)\n"
            "    ax.set_title(f'{column} by cohort')\n"
            "    ax.set_ylabel(column)\n"
            "    ax.grid(alpha=0.2)\n"
            "    fig.tight_layout()\n"
            "    fig.savefig(FIGURES_DIR / f'{column}_by_cohort.png', dpi=220)\n"
            "    plt.close(fig)\n\n"
            "top_cases = structure_metrics[structure_metrics['cohort'] == 'repair_exemplar'].sort_values(['pair_repair', 'site_contact_count'], ascending=False).head(TOP_CASES)\n"
            "if top_cases.empty:\n"
            "    top_cases = structure_metrics.sort_values(['pair_repair', 'site_contact_count'], ascending=False).head(TOP_CASES)\n"
            "for row in top_cases.to_dict(orient='records'):\n"
            "    payload = contact_maps.get(row['variant_id'])\n"
            "    if not payload:\n"
            "        continue\n"
            "    matrix = np.asarray(payload['contact_map'], dtype=float)\n"
            "    if matrix.size == 0:\n"
            "        continue\n"
            "    fig, ax = plt.subplots(figsize=(5.5, 4.8))\n"
            "    image = ax.imshow(matrix, cmap='magma', aspect='auto')\n"
            "    ax.set_title(f\"{row['variant_id']} local WT contact map\")\n"
            "    ax.set_xlabel('Window residue index')\n"
            "    ax.set_ylabel('Window residue index')\n"
            "    fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)\n"
            "    fig.tight_layout()\n"
            "    safe_name = row['variant_id'].replace(':', '_').replace('>', '_')\n"
            "    fig.savefig(FIGURES_DIR / f'contact_map_{safe_name}.png', dpi=220)\n"
            "    plt.close(fig)\n\n"
            "display(cohort_summary)\n"
            "display(core_readout)\n"
            "done('Bridge summaries and figures saved.')\n"
        ),
        code_cell(
            "# Write markdown/json summaries and package the final bundle\n"
            "repair_row = cohort_summary[cohort_summary['cohort'] == 'repair_exemplar']\n"
            "control_row = cohort_summary[cohort_summary['cohort'] == 'matched_control']\n"
            "repair_contacts = float(repair_row['median_site_contacts'].iloc[0]) if not repair_row.empty else float('nan')\n"
            "control_contacts = float(control_row['median_site_contacts'].iloc[0]) if not control_row.empty else float('nan')\n"
            "reference_contacts = float(reference_row['median_site_contacts'].iloc[0]) if not reference_row.empty else float('nan')\n"
            "pair_vs_contacts = float(core_readout.loc[core_readout['metric_name'] == 'pair_repair_vs_site_contact_count', 'value'].iloc[0])\n"
            "pair_vs_plddt = float(core_readout.loc[core_readout['metric_name'] == 'pair_repair_vs_window_plddt_mean', 'value'].iloc[0])\n\n"
            "claim_status = 'weak_wt_structure_bridge'\n"
            "claim_reason = 'WT local structure signals were mixed; keep the structure bridge as supporting evidence only.'\n"
            "if not math.isnan(repair_contacts) and not math.isnan(control_contacts) and repair_contacts > control_contacts and (math.isnan(pair_vs_contacts) or pair_vs_contacts >= 0.2):\n"
            "    claim_status = 'wt_structure_bridge_supported'\n"
            "    claim_reason = 'Repair exemplars concentrate in more contact-dense WT neighborhoods, supporting a local structural tension interpretation.'\n\n"
            "elif not math.isnan(repair_window_contact) and not math.isnan(reference_window_contact) and repair_window_contact > reference_window_contact:\n"
            "    claim_status = 'bounded_wt_structure_bridge'\n"
            "    claim_reason = 'Repair exemplars sit in denser WT structural neighborhoods than likelihood-driven references, but the matched-control bridge is still mixed.'\n\n"
            "top_table = structure_metrics.sort_values(['pair_repair', 'site_contact_count'], ascending=False).head(5)[[\n"
            "    'cohort', 'gene', 'variant_id', 'pair_repair', 'frob_repair', 'll_repair', 'site_plddt', 'window_plddt_mean', 'site_contact_count', 'site_long_range_contact_count'\n"
            "]].copy()\n"
            "top_table.to_csv(TABLES_DIR / 'top_structure_bridge_cases.csv', index=False)\n\n"
            "summary_payload = {\n"
            "    'notebook_slug': NOTEBOOK_SLUG,\n"
            "    'account_label': ACCOUNT_LABEL,\n"
            "    'run_at_utc': RUN_AT,\n"
            "    'head_commit': repo_status['head_commit'],\n"
            "    'claim_status': claim_status,\n"
            "    'claim_reason': claim_reason,\n"
            "    'n_selected_variants': int(len(selected_variants)),\n"
            "    'n_structured_variants': int(len(structure_metrics)),\n"
            "    'repair_exemplar_median_contacts': repair_contacts,\n"
            "    'matched_control_median_contacts': control_contacts,\n"
            "    'likelihood_reference_median_contacts': reference_contacts,\n"
            "    'repair_exemplar_median_window_contact_mean': repair_window_contact,\n"
            "    'likelihood_reference_median_window_contact_mean': reference_window_contact,\n"
            "    'pair_repair_vs_site_contact_count_spearman': pair_vs_contacts,\n"
            "    'pair_repair_vs_window_plddt_spearman': pair_vs_plddt,\n"
            "    'top_variants': top_table.to_dict(orient='records'),\n"
            "}\n"
            "(MANIFESTS_DIR / 'block5_summary.json').write_text(json.dumps(summary_payload, indent=2), encoding='utf-8')\n"
            "(MANIFESTS_DIR / 'artifact_summary.json').write_text(json.dumps(summary_payload, indent=2), encoding='utf-8')\n\n"
            "summary_md = '\\n'.join([\n"
            "    '# Block 3 Structure Bridge Summary',\n"
            "    '',\n"
            "    f\"- Claim status: `{claim_status}`\",\n"
            "    f\"- Claim reason: {claim_reason}\",\n"
            "    f\"- Structured variants analyzed: `{len(structure_metrics)}` of `{len(selected_variants)}` selected rows\",\n"
            "    f\"- Repair exemplar median site contacts: `{repair_contacts:.3f}`\" if not math.isnan(repair_contacts) else '- Repair exemplar median site contacts: `nan`',\n"
            "    f\"- Matched control median site contacts: `{control_contacts:.3f}`\" if not math.isnan(control_contacts) else '- Matched control median site contacts: `nan`',\n"
            "    f\"- Likelihood-reference median site contacts: `{reference_contacts:.3f}`\" if not math.isnan(reference_contacts) else '- Likelihood-reference median site contacts: `nan`',\n"
            "    f\"- Repair exemplar median window contact mean: `{repair_window_contact:.3f}`\" if not math.isnan(repair_window_contact) else '- Repair exemplar median window contact mean: `nan`',\n"
            "    f\"- Likelihood-reference median window contact mean: `{reference_window_contact:.3f}`\" if not math.isnan(reference_window_contact) else '- Likelihood-reference median window contact mean: `nan`',\n"
            "    f\"- Spearman(pair_repair, site_contact_count): `{pair_vs_contacts:.3f}`\" if not math.isnan(pair_vs_contacts) else '- Spearman(pair_repair, site_contact_count): `nan`',\n"
            "    f\"- Spearman(pair_repair, window_plddt_mean): `{pair_vs_plddt:.3f}`\" if not math.isnan(pair_vs_plddt) else '- Spearman(pair_repair, window_plddt_mean): `nan`',\n"
            "])\n"
            "(TEXT_DIR / 'block5_summary.md').write_text(summary_md + '\\n', encoding='utf-8')\n\n"
            "if ZIP_PATH.exists():\n"
            "    ZIP_PATH.unlink()\n"
            "if ROOT_ZIP_COPY.exists():\n"
            "    ROOT_ZIP_COPY.unlink()\n"
            "with zipfile.ZipFile(ZIP_PATH, 'w', compression=zipfile.ZIP_DEFLATED) as archive:\n"
            "    for path in sorted(RESULTS_ROOT.rglob('*')):\n"
            "        if path.is_file():\n"
            "            archive.write(path, path.relative_to(RESULTS_ROOT.parent))\n"
            "shutil.copy2(ZIP_PATH, ROOT_ZIP_COPY)\n"
            "print(summary_md)\n"
            "done('Block 3 bundle is ready for download.')\n"
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    notebook = build_notebook()
    output_path = repo_root / "New Notebooks" / "05_block3_structure_bridge_h100.ipynb"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
    print(f"Wrote notebook to {output_path}")


if __name__ == "__main__":
    main()
