from __future__ import annotations

import json
from pathlib import Path


def markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.splitlines(keepends=True),
    }


def build_notebook() -> dict:
    cells: list[dict] = [
        markdown_cell(
            "# Experiment: SpectralBio Block 4 - Model-Agnostic PLMs (H100)\n\n"
            "Objective:\n"
            "- Test whether the covariance audit survives outside the exact ESM2-150M checkpoint used in the original story.\n"
            "- Reuse the strongest frozen ESM-family evidence first, then add bounded live runs that fit a single H100 session.\n"
            "- Combine anchor-gene full-surface results with a cross-family failure-mode subset audit.\n"
            "- Save a complete Lightning-friendly bundle under `New Notebooks/results/03_block4_model_agnostic_plms_h100_v2/`.\n"
        ),
        markdown_cell(
            "## Block 4 Deliverables\n\n"
            "- Anchor-gene summary for `TP53`, `BRCA2`, `BRCA1`, and `MSH2` across frozen and live model variants.\n"
            "- A lightweight `ESM2-35M` live sweep on the same four genes to test whether the signal is not a one-checkpoint quirk.\n"
            "- Reused `ESM2-150M`, `ESM2-650M`, and `ESM-1v` evidence where it already exists.\n"
            "- A bounded cross-family `ProtT5` subset audit on the Block 2 candidate/control pool.\n"
            "- A reviewer-facing claim that degrades honestly to `family-bounded` if the cross-family signal is weak.\n\n"
            "## Runtime contract\n\n"
            "- Target environment: **Lightning AI Studio**\n"
            "- Target hardware: **H100**\n"
            "- Full-panel reruns are intentionally avoided.\n"
            "- All outputs are written under `New Notebooks/results/03_block4_model_agnostic_plms_h100_v2/`.\n"
        ),
        code_cell(
            "# Setup: imports, identifiers, and notebook knobs\n"
            "from __future__ import annotations\n\n"
            "import importlib\n"
            "import json\n"
            "import math\n"
            "import os\n"
            "import platform\n"
            "import re\n"
            "import shutil\n"
            "import subprocess\n"
            "import sys\n"
            "import time\n"
            "import zipfile\n"
            "from datetime import datetime, timezone\n"
            "from pathlib import Path\n\n"
            "import matplotlib.pyplot as plt\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "from IPython.display import display\n"
            "from sklearn.metrics import roc_auc_score\n\n"
            "NOTEBOOK_SLUG = '03_block4_model_agnostic_plms_h100_v2'\n"
            "ACCOUNT_LABEL = os.environ.get('SPECTRALBIO_ACCOUNT_LABEL', 'SET_ACCOUNT_LABEL_HERE')\n"
            "RUN_AT = datetime.now(timezone.utc).isoformat()\n"
            "SEED = int(os.environ.get('SPECTRALBIO_RANDOM_SEED', '42'))\n"
            "OVERWRITE = os.environ.get('SPECTRALBIO_OVERWRITE', '').strip().lower() in {'1', 'true', 'yes'}\n"
            "ANCHOR_GENES = tuple(\n"
            "    gene.strip().upper()\n"
            "    for gene in os.environ.get('SPECTRALBIO_BLOCK4_GENES', 'TP53,BRCA2,BRCA1,MSH2').split(',')\n"
            "    if gene.strip()\n"
            ")\n"
            "LIGHT_MODEL_NAME = os.environ.get('SPECTRALBIO_BLOCK4_LIGHT_MODEL', 'facebook/esm2_t12_35M_UR50D').strip()\n"
            "PROTT5_MODEL_NAME = os.environ.get('SPECTRALBIO_BLOCK4_PROTT5_MODEL', 'Rostlab/prot_t5_xl_half_uniref50-enc').strip()\n"
            "PAIR_ALPHA = float(os.environ.get('SPECTRALBIO_BLOCK4_PAIR_ALPHA', '0.55'))\n"
            "WINDOW_RADIUS = int(os.environ.get('SPECTRALBIO_BLOCK4_WINDOW_RADIUS', '40'))\n"
            "CHECKPOINT_EVERY = int(os.environ.get('SPECTRALBIO_BLOCK4_CHECKPOINT_EVERY', '25'))\n"
            "RUN_PROTT5_SUBSET = os.environ.get('SPECTRALBIO_BLOCK4_RUN_PROTT5_SUBSET', '1').strip().lower() in {'1', 'true', 'yes'}\n"
            "PROTT5_LAYER_PROTOCOL = os.environ.get('SPECTRALBIO_BLOCK4_PROTT5_LAYER_PROTOCOL', 'last4').strip().lower()\n\n"
            "def done(message: str) -> None:\n"
            "    print(f'TERMINEI PODE SEGUIR - {message}')\n\n"
            "print({\n"
            "    'notebook_slug': NOTEBOOK_SLUG,\n"
            "    'account_label': ACCOUNT_LABEL,\n"
            "    'seed': SEED,\n"
            "    'anchor_genes': ANCHOR_GENES,\n"
            "    'light_model_name': LIGHT_MODEL_NAME,\n"
            "    'prott5_model_name': PROTT5_MODEL_NAME,\n"
            "    'pair_alpha': PAIR_ALPHA,\n"
            "    'window_radius': WINDOW_RADIUS,\n"
            "    'run_prott5_subset': RUN_PROTT5_SUBSET,\n"
            "    'prott5_layer_protocol': PROTT5_LAYER_PROTOCOL,\n"
            "    'overwrite': OVERWRITE,\n"
            "    'python': sys.version.split()[0],\n"
            "    'platform': platform.platform(),\n"
            "})\n"
            "done('Initial configuration loaded.')\n"
        ),
        code_cell(
            "# Helpers: subprocess, repo discovery, path resolution, table utilities, and basic metrics\n"
            "def run(command: list[str], cwd: Path | None = None, check: bool = True) -> str:\n"
            "    completed = subprocess.run(\n"
            "        command,\n"
            "        cwd=str(cwd) if cwd is not None else None,\n"
            "        check=check,\n"
            "        text=True,\n"
            "        encoding='utf-8',\n"
            "        errors='replace',\n"
            "        capture_output=True,\n"
            "    )\n"
            "    if completed.stdout.strip():\n"
            "        print(completed.stdout.strip())\n"
            "    if completed.stderr.strip():\n"
            "        print(completed.stderr.strip())\n"
            "    return completed.stdout\n\n"
            "def ensure_dir(path: Path) -> Path:\n"
            "    path.mkdir(parents=True, exist_ok=True)\n"
            "    return path\n\n"
            "def looks_like_repo(path: Path) -> bool:\n"
            "    return (path / 'src' / 'spectralbio').exists() and (path / 'notebooks').exists()\n\n"
            "def find_repo_root() -> Path:\n"
            "    env_repo = os.environ.get('SPECTRALBIO_REPO_ROOT', '').strip()\n"
            "    candidates: list[Path] = []\n"
            "    if env_repo:\n"
            "        candidates.append(Path(env_repo).expanduser())\n"
            "    cwd = Path.cwd().resolve()\n"
            "    candidates.extend([\n"
            "        cwd,\n"
            "        cwd.parent,\n"
            "        Path('/teamspace/studios/this_studio/Stanford-Claw4s'),\n"
            "        Path('/teamspace/studios/this_studio/SpectralBio'),\n"
            "        Path('/content/Stanford-Claw4s'),\n"
            "    ])\n"
            "    for candidate in candidates:\n"
            "        if looks_like_repo(candidate):\n"
            "            return candidate.resolve()\n"
            "    raise FileNotFoundError('Could not locate the SpectralBio repository root. Set SPECTRALBIO_REPO_ROOT or run inside the repo.')\n\n"
            "def resolve_existing_path(raw: str | Path, repo_root: Path) -> Path:\n"
            "    raw_path = Path(raw)\n"
            "    if raw_path.exists():\n"
            "        return raw_path.resolve()\n"
            "    raw_text = str(raw).replace('\\\\', '/')\n"
            "    for prefix in ('/content/Stanford-Claw4s/', '/teamspace/studios/this_studio/Stanford-Claw4s/', '/teamspace/studios/this_studio/SpectralBio/'):\n"
            "        if raw_text.startswith(prefix):\n"
            "            candidate = repo_root / raw_text[len(prefix):]\n"
            "            if candidate.exists():\n"
            "                return candidate.resolve()\n"
            "    if 'Stanford-Claw4s/' in raw_text:\n"
            "        candidate = repo_root / raw_text.split('Stanford-Claw4s/', 1)[1]\n"
            "        if candidate.exists():\n"
            "            return candidate.resolve()\n"
            "    if not raw_path.is_absolute():\n"
            "        candidate = (repo_root / raw_path).resolve()\n"
            "        if candidate.exists():\n"
            "            return candidate\n"
            "    return raw_path\n\n"
            "def find_first_existing_path(candidates: list[str | Path], repo_root: Path) -> Path | None:\n"
            "    for candidate in candidates:\n"
            "        resolved = resolve_existing_path(candidate, repo_root)\n"
            "        if resolved.exists():\n"
            "            return resolved\n"
            "    return None\n\n"
            "def safe_float(value, default: float = float('nan')) -> float:\n"
            "    try:\n"
            "        return float(value)\n"
            "    except Exception:\n"
            "        return default\n\n"
            "def auc_safe(y_true, y_score) -> float:\n"
            "    y_true = np.asarray(y_true, dtype=int)\n"
            "    y_score = np.asarray(y_score, dtype=float)\n"
            "    if len(np.unique(y_true)) < 2:\n"
            "        return float('nan')\n"
            "    return float(roc_auc_score(y_true, y_score))\n\n"
            "def normalize_series(series: pd.Series) -> pd.Series:\n"
            "    values = series.astype(float)\n"
            "    minimum = float(values.min())\n"
            "    maximum = float(values.max())\n"
            "    if maximum <= minimum:\n"
            "        return pd.Series(np.zeros(len(values), dtype=float), index=series.index)\n"
            "    return (values - minimum) / (maximum - minimum)\n\n"
            "def pair_from_columns(frame: pd.DataFrame, frob_col: str, scalar_col: str, alpha: float = PAIR_ALPHA) -> pd.Series:\n"
            "    frob_norm = normalize_series(frame[frob_col])\n"
            "    scalar_norm = normalize_series(frame[scalar_col])\n"
            "    return alpha * frob_norm + (1.0 - alpha) * scalar_norm\n\n"
            "done('Helpers ready.')\n"
        ),
        code_cell(
            "# Resolve repository root and output directories\n"
            "REPO_ROOT = find_repo_root()\n"
            "RESULTS_ROOT = ensure_dir(REPO_ROOT / 'New Notebooks' / 'results' / NOTEBOOK_SLUG)\n"
            "TABLES_DIR = ensure_dir(RESULTS_ROOT / 'tables')\n"
            "FIGURES_DIR = ensure_dir(RESULTS_ROOT / 'figures')\n"
            "TEXT_DIR = ensure_dir(RESULTS_ROOT / 'text')\n"
            "MANIFESTS_DIR = ensure_dir(RESULTS_ROOT / 'manifests')\n"
            "RUNTIME_DIR = ensure_dir(RESULTS_ROOT / 'runtime')\n"
            "LIVE_SCORES_DIR = ensure_dir(RESULTS_ROOT / 'live_scores')\n"
            "ZIP_PATH = REPO_ROOT / 'New Notebooks' / 'results' / f'{NOTEBOOK_SLUG}.zip'\n"
            "ROOT_ZIP_COPY = REPO_ROOT / 'New Notebooks' / f'{NOTEBOOK_SLUG}.zip'\n"
            "repo_status = {\n"
            "    'repo_root': str(REPO_ROOT),\n"
            "    'head_commit': run(['git', 'rev-parse', 'HEAD'], cwd=REPO_ROOT).strip(),\n"
            "    'head_subject': run(['git', 'log', '-1', '--pretty=%s'], cwd=REPO_ROOT).strip(),\n"
            "    'branch': run(['git', 'branch', '--show-current'], cwd=REPO_ROOT).strip(),\n"
            "}\n"
            "display(pd.DataFrame([repo_status]))\n"
            "done('Repository and output directories confirmed.')\n"
        ),
        code_cell(
            "# Lightning preflight: install runtime dependencies in the active kernel and clear stale import state when needed\n"
            "RUNTIME_REQUIREMENTS = [\n"
            "    ('numpy', 'numpy==2.1.3'),\n"
            "    ('pandas', 'pandas==2.2.3'),\n"
            "    ('matplotlib', 'matplotlib==3.9.2'),\n"
            "    ('sklearn', 'scikit-learn==1.5.2'),\n"
            "    ('torch', 'torch'),\n"
            "    ('transformers', 'transformers==4.49.0'),\n"
            "    ('accelerate', 'accelerate>=1.0.0'),\n"
            "    ('sentencepiece', 'sentencepiece>=0.2.0'),\n"
            "    ('google.protobuf', 'protobuf>=5'),\n"
            "    ('safetensors', 'safetensors>=0.4.0'),\n"
            "]\n"
            "runtime_rows = []\n"
            "missing_packages: list[str] = []\n"
            "for module_name, package_spec in RUNTIME_REQUIREMENTS:\n"
            "    try:\n"
            "        importlib.import_module(module_name)\n"
            "        runtime_rows.append({'module': module_name, 'status': 'ok', 'package_spec': package_spec})\n"
            "    except Exception as exc:\n"
            "        runtime_rows.append({'module': module_name, 'status': f'missing:{type(exc).__name__}', 'package_spec': package_spec})\n"
            "        missing_packages.append(package_spec)\n"
            "display(pd.DataFrame(runtime_rows))\n"
            "if missing_packages:\n"
            "    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--quiet', '--upgrade', *missing_packages])\n"
            "    modules_to_drop = [\n"
            "        name for name in list(sys.modules)\n"
            "        if name == 'accelerate'\n"
            "        or name.startswith('accelerate.')\n"
            "        or name == 'transformers'\n"
            "        or name.startswith('transformers.')\n"
            "        or name == 'spectralbio'\n"
            "        or name.startswith('spectralbio.')\n"
            "    ]\n"
            "    for name in modules_to_drop:\n"
            "        sys.modules.pop(name, None)\n"
            "    importlib.invalidate_caches()\n"
            "    print('Installed runtime packages:', ', '.join(missing_packages))\n"
            "import accelerate\n"
            "import torch\n"
            "from transformers.utils.import_utils import is_accelerate_available\n"
            "runtime_manifest = {\n"
            "    'python': sys.version.split()[0],\n"
            "    'torch_version': getattr(torch, '__version__', 'unknown'),\n"
            "    'accelerate_version': getattr(accelerate, '__version__', 'unknown'),\n"
            "    'cuda_available': bool(torch.cuda.is_available()),\n"
            "    'cuda_device_count': int(torch.cuda.device_count()) if torch.cuda.is_available() else 0,\n"
            "    'transformers_sees_accelerate': bool(is_accelerate_available()),\n"
            "    'account_label': ACCOUNT_LABEL,\n"
            "    'run_at': RUN_AT,\n"
            "}\n"
            "(RUNTIME_DIR / 'runtime_manifest.json').write_text(json.dumps(runtime_manifest, indent=2), encoding='utf-8')\n"
            "display(pd.DataFrame([runtime_manifest]))\n"
            "done('Runtime dependencies are ready for Lightning.')\n"
        ),
        code_cell(
            "# Import local SpectralBio helpers after runtime preflight\n"
            "src_path = REPO_ROOT / 'src'\n"
            "if str(src_path) not in sys.path:\n"
            "    sys.path.insert(0, str(src_path))\n"
            "subprocess.run([sys.executable, '-m', 'pip', 'install', '-e', '.', '--no-deps'], cwd=str(REPO_ROOT), check=False)\n"
            "from spectralbio.supplementary.reject_recovery import covariance_features_dual, _ensure_gene_score_rows, _score_rows_summary\n"
            "done('Local package imports are clean inside Lightning.')\n"
        ),
        code_cell(
            "# Locate frozen evidence and anchor-gene sources\n"
            "BLOCK1_SYNTHETIC_SUMMARY_ROWS = [\n"
            "    {\n"
            "        'gene': 'TP53',\n"
            "        'auc_esm1v_mean': 0.9465838509316771,\n"
            "        'auc_augmented_pair_fixed_055': 0.9304968944099379,\n"
            "        'delta_augmented_vs_esm1v': -0.016086956521739193,\n"
            "    },\n"
            "    {\n"
            "        'gene': 'BRCA2',\n"
            "        'auc_esm1v_mean': 0.6323835125448029,\n"
            "        'auc_augmented_pair_fixed_055': 0.6889784946236559,\n"
            "        'delta_augmented_vs_esm1v': 0.05659498207885305,\n"
            "    },\n"
            "    {\n"
            "        'gene': 'MSH2',\n"
            "        'auc_esm1v_mean': 0.9232531841447447,\n"
            "        'auc_augmented_pair_fixed_055': 0.8457028925127961,\n"
            "        'delta_augmented_vs_esm1v': -0.0775502916319486,\n"
            "    },\n"
            "]\n"
            "def ensure_block4_bootstrap_artifacts(repo_root: Path) -> dict[str, str]:\n"
            "    bootstrap_notes: dict[str, str] = {}\n"
            "    block1_target = ensure_dir(repo_root / 'New Notebooks' / 'results' / '01_block1_baseline_alpha_regime_audit_h100' / 'tables') / 'reviewer_facing_summary_table.csv'\n"
            "    block2_target = ensure_dir(repo_root / 'New Notebooks' / 'results' / '02_block2_failure_mode_hunt_h100' / 'tables') / 'annotated_failure_mode_rows.csv'\n"
            "    if not block1_target.exists():\n"
            "        block1_candidates = [\n"
            "            repo_root / 'New Notebooks' / 'results' / '01_block1_baseline_alpha_regime_audit_h100' / 'tables' / 'reviewer_facing_summary_table.csv',\n"
            "        ]\n"
            "        copied = None\n"
            "        for candidate in block1_candidates:\n"
            "            if candidate.exists() and candidate.resolve() != block1_target.resolve():\n"
            "                copied = candidate\n"
            "                break\n"
            "        if copied is None:\n"
            "            for candidate in repo_root.rglob('reviewer_facing_summary_table.csv'):\n"
            "                if candidate.exists() and candidate.resolve() != block1_target.resolve():\n"
            "                    copied = candidate\n"
            "                    break\n"
            "        if copied is not None:\n"
            "            shutil.copy2(copied, block1_target)\n"
            "            bootstrap_notes['block1_reviewer_summary'] = f'copied:{copied}'\n"
            "        else:\n"
            "            pd.DataFrame(BLOCK1_SYNTHETIC_SUMMARY_ROWS).to_csv(block1_target, index=False)\n"
            "            bootstrap_notes['block1_reviewer_summary'] = 'synthesized:minimal_block1_reviewer_summary'\n"
            "    else:\n"
            "        bootstrap_notes['block1_reviewer_summary'] = f'existing:{block1_target}'\n"
            "    if not block2_target.exists():\n"
            "        block2_candidates = [\n"
            "            repo_root / 'New Notebooks' / 'results' / '02_block2_failure_mode_hunt_h100' / 'tables' / 'annotated_failure_mode_rows.csv',\n"
            "            repo_root / 'New Notebooks' / 'results' / '02_block2_failure_mode_hunt_h100' / 'tables' / 'failure_mode_validation_rows_reused_or_rerun.csv',\n"
            "            repo_root / 'supplementary' / 'failure_mode_validation_h100' / 'failure_mode_validation' / 'tables' / 'failure_mode_validation_rows.csv',\n"
            "            repo_root / 'notebooks' / 'Results 7,8,9' / 'failure_mode_validation_bundle' / 'tables' / 'failure_mode_validation_rows.csv',\n"
            "        ]\n"
            "        copied = None\n"
            "        for candidate in block2_candidates:\n"
            "            if candidate.exists() and candidate.resolve() != block2_target.resolve():\n"
            "                copied = candidate\n"
            "                break\n"
            "        if copied is not None:\n"
            "            shutil.copy2(copied, block2_target)\n"
            "            bootstrap_notes['block2_rows'] = f'copied:{copied}'\n"
            "        else:\n"
            "            raise FileNotFoundError('Could not bootstrap Block 2 rows for Block 4. Expected a failure-mode validation table in supplementary/ or prior notebook outputs.')\n"
            "    else:\n"
            "        bootstrap_notes['block2_rows'] = f'existing:{block2_target}'\n"
            "    required_block1_cols = {'gene', 'auc_esm1v_mean', 'auc_augmented_pair_fixed_055', 'delta_augmented_vs_esm1v'}\n"
            "    required_block2_cols = {'gene', 'position', 'wt_aa', 'mut_aa', 'label', 'validation_role'}\n"
            "    block1_cols = set(pd.read_csv(block1_target, nrows=1).columns)\n"
            "    block2_cols = set(pd.read_csv(block2_target, nrows=1).columns)\n"
            "    missing_block1_cols = sorted(required_block1_cols - block1_cols)\n"
            "    missing_block2_cols = sorted(required_block2_cols - block2_cols)\n"
            "    if missing_block1_cols:\n"
            "        raise ValueError(f'Bootstrapped Block 1 reviewer summary is missing columns: {missing_block1_cols}')\n"
            "    if missing_block2_cols:\n"
            "        raise ValueError(f'Bootstrapped Block 2 rows are missing columns: {missing_block2_cols}')\n"
            "    return bootstrap_notes\n"
            "bootstrap_notes = ensure_block4_bootstrap_artifacts(REPO_ROOT)\n"
            "FROZEN_PATH_CANDIDATES = {\n"
            "    'reject_backbone_tp53_csv': [\n"
            "        REPO_ROOT / 'notebooks' / 'Results' / 'spectralbio_reject_recovery_bundle' / 'backbone_strength' / 'tp53_backbone_comparison.csv',\n"
            "        REPO_ROOT / 'notebooks' / 'Final Results 1 e 2' / 'part2_key_results' / 'tp53_backbone_comparison.csv',\n"
            "    ],\n"
            "    'reject_backbone_tp53_json': [\n"
            "        REPO_ROOT / 'notebooks' / 'Results' / 'spectralbio_reject_recovery_bundle' / 'backbone_strength' / 'tp53_backbone_metrics.json',\n"
            "        REPO_ROOT / 'notebooks' / 'Final Results 1 e 2' / 'part2_key_results' / 'tp53_backbone_metrics.json',\n"
            "    ],\n"
            "    'reject_multigene_summary': [\n"
            "        REPO_ROOT / 'notebooks' / 'Results' / 'spectralbio_reject_recovery_bundle' / 'multigene' / 'multigene_summary.csv',\n"
            "        REPO_ROOT / 'supplementary' / 'final_accept_a100' / 'panel25' / 'multigene' / 'multigene_summary.csv',\n"
            "    ],\n"
            "    'reject_panel_manifest': [\n"
            "        REPO_ROOT / 'notebooks' / 'Results' / 'spectralbio_reject_recovery_bundle' / 'multigene' / 'panel_manifest.json',\n"
            "        REPO_ROOT / 'supplementary' / 'final_accept_a100' / 'panel25' / 'support_ranked_panel_manifest.json',\n"
            "    ],\n"
            "    'block1_reviewer_summary': [\n"
            "        REPO_ROOT / 'New Notebooks' / 'results' / '01_block1_baseline_alpha_regime_audit_h100' / 'tables' / 'reviewer_facing_summary_table.csv',\n"
            "        REPO_ROOT / 'artifacts' / 'release' / 'claw4s_2026' / 'notebook_results' / '01_block1_baseline_alpha_regime_audit_h100' / 'tables' / 'reviewer_facing_summary_table.csv',\n"
            "    ],\n"
            "    'block2_rows': [\n"
            "        REPO_ROOT / 'New Notebooks' / 'results' / '02_block2_failure_mode_hunt_h100' / 'tables' / 'annotated_failure_mode_rows.csv',\n"
            "        REPO_ROOT / 'New Notebooks' / 'results' / '02_block2_failure_mode_hunt_h100' / 'tables' / 'failure_mode_validation_rows_reused_or_rerun.csv',\n"
            "        REPO_ROOT / 'supplementary' / 'failure_mode_validation_h100' / 'failure_mode_validation' / 'tables' / 'failure_mode_validation_rows.csv',\n"
            "        REPO_ROOT / 'notebooks' / 'Results 7,8,9' / 'failure_mode_validation_bundle' / 'tables' / 'failure_mode_validation_rows.csv',\n"
            "    ],\n"
            "}\n"
            "artifact_rows = []\n"
            "resolved_artifacts: dict[str, Path | None] = {}\n"
            "for key, candidates in FROZEN_PATH_CANDIDATES.items():\n"
            "    resolved = find_first_existing_path(candidates, REPO_ROOT)\n"
            "    resolved_artifacts[key] = resolved\n"
            "    artifact_rows.append({'artifact_key': key, 'resolved_path': str(resolved) if resolved else '', 'exists': resolved is not None, 'bootstrap_note': bootstrap_notes.get(key, '')})\n"
            "artifact_inventory = pd.DataFrame(artifact_rows)\n"
            "artifact_inventory.to_csv(TABLES_DIR / 'frozen_evidence_inventory.csv', index=False)\n"
            "display(artifact_inventory)\n"
            "required_keys = ['reject_multigene_summary', 'reject_panel_manifest', 'block1_reviewer_summary', 'block2_rows']\n"
            "missing_required = [key for key in required_keys if resolved_artifacts.get(key) is None]\n"
            "if missing_required:\n"
            "    raise FileNotFoundError(f'Missing required frozen artifacts for Block 4: {missing_required}')\n"
            "done('Frozen evidence inventory saved.')\n"
        ),
        code_cell(
            "# Load panel manifest, anchor gene variants, and the frozen summaries\n"
            "panel_manifest = json.loads(Path(resolved_artifacts['reject_panel_manifest']).read_text(encoding='utf-8'))\n"
            "def find_repo_file(candidates: list[Path]) -> Path | None:\n"
            "    for candidate in candidates:\n"
            "        if candidate.exists():\n"
            "            return candidate.resolve()\n"
            "    return None\n\n"
            "def materialize_variants_from_scores(score_csv_path: Path, output_json_path: Path) -> Path:\n"
            "    scores = pd.read_csv(score_csv_path)\n"
            "    required = ['gene', 'name', 'position', 'wt_aa', 'mut_aa', 'label']\n"
            "    missing = [column for column in required if column not in scores.columns]\n"
            "    if missing:\n"
            "        raise ValueError(f'Cannot materialize variants from {score_csv_path}: missing columns {missing}')\n"
            "    variant_rows = scores.loc[:, required].copy()\n"
            "    variant_rows['position'] = variant_rows['position'].astype(int)\n"
            "    variant_rows['label'] = variant_rows['label'].astype(int)\n"
            "    output_json_path.write_text(json.dumps(variant_rows.to_dict(orient='records'), indent=2), encoding='utf-8')\n"
            "    return output_json_path\n\n"
            "def resolve_anchor_inputs(gene: str, gene_info: dict, repo_root: Path) -> tuple[Path | None, Path | None, str]:\n"
            "    variants_raw = str(gene_info.get('variants_path', ''))\n"
            "    sequence_raw = str(gene_info.get('sequence_path', ''))\n"
            "    variant_candidates = []\n"
            "    if variants_raw:\n"
            "        variant_candidates.append(resolve_existing_path(variants_raw, repo_root))\n"
            "    if gene == 'TP53':\n"
            "        variant_candidates.extend([\n"
            "            repo_root / 'legacy' / 'huggingface_data' / 'tp53_variants.json',\n"
            "            repo_root / 'legacy' / 'colab_results' / 'tp53_variants.json',\n"
            "        ])\n"
            "    elif gene == 'BRCA1':\n"
            "        variant_candidates.extend([\n"
            "            repo_root / 'benchmarks' / 'brca1' / 'brca1_full_filtered_v1.json',\n"
            "            repo_root / 'artifacts' / 'release' / 'claw4s_2026' / 'hf_dataset' / 'benchmarks' / 'brca1' / 'brca1_full_filtered_v1.json',\n"
            "            repo_root / 'artifacts' / 'release' / 'claw4s_2026' / 'hf_space' / 'benchmarks' / 'brca1' / 'brca1_full_filtered_v1.json',\n"
            "        ])\n"
            "    variant_path = find_repo_file(variant_candidates)\n"
            "    variant_note = 'direct' if variant_path is not None else 'missing_direct_variants'\n"
            "    if variant_path is None and gene in {'BRCA2', 'MSH2'}:\n"
            "        score_csv_name = f\"{gene.lower()}_facebook_esm2_t30_150M_UR50D_scores.csv\"\n"
            "        score_candidates = [\n"
            "            repo_root / 'supplementary' / 'final_accept_a100' / 'panel25' / 'multigene' / gene.lower() / score_csv_name,\n"
            "        ]\n"
            "        score_path = find_repo_file(score_candidates)\n"
            "        if score_path is not None:\n"
            "            runtime_json_path = RUNTIME_DIR / f'{gene.lower()}_variants_from_scores.json'\n"
            "            variant_path = materialize_variants_from_scores(score_path, runtime_json_path)\n"
            "            variant_note = f'materialized_from_scores:{score_path.name}'\n"
            "    sequence_candidates = []\n"
            "    if sequence_raw:\n"
            "        sequence_candidates.append(resolve_existing_path(sequence_raw, repo_root))\n"
            "    if gene == 'TP53':\n"
            "        sequence_candidates.extend([\n"
            "            repo_root / 'benchmarks' / 'sequences' / 'tp53.fasta',\n"
            "            repo_root / 'artifacts' / 'release' / 'claw4s_2026' / 'hf_dataset' / 'benchmarks' / 'sequences' / 'tp53.fasta',\n"
            "            repo_root / 'artifacts' / 'release' / 'claw4s_2026' / 'hf_space' / 'benchmarks' / 'sequences' / 'tp53.fasta',\n"
            "        ])\n"
            "    elif gene == 'BRCA1':\n"
            "        sequence_candidates.extend([\n"
            "            repo_root / 'benchmarks' / 'sequences' / 'brca1.fasta',\n"
            "            repo_root / 'artifacts' / 'release' / 'claw4s_2026' / 'hf_dataset' / 'benchmarks' / 'sequences' / 'brca1.fasta',\n"
            "            repo_root / 'artifacts' / 'release' / 'claw4s_2026' / 'hf_space' / 'benchmarks' / 'sequences' / 'brca1.fasta',\n"
            "        ])\n"
            "    elif gene == 'BRCA2':\n"
            "        sequence_candidates.append(repo_root / 'supplementary' / 'final_accept_a100' / 'panel25' / 'cache' / 'uniprot' / 'brca2.fasta')\n"
            "    elif gene == 'MSH2':\n"
            "        sequence_candidates.append(repo_root / 'supplementary' / 'final_accept_a100' / 'panel25' / 'cache' / 'uniprot' / 'msh2.fasta')\n"
            "    sequence_path = find_repo_file(sequence_candidates)\n"
            "    sequence_note = 'direct' if sequence_path is not None else 'missing_sequence'\n"
            "    return variant_path, sequence_path, f'{variant_note}|{sequence_note}'\n\n"
            "anchor_gene_rows = []\n"
            "anchor_variants: dict[str, list[dict]] = {}\n"
            "anchor_sequences: dict[str, str] = {}\n"
            "dropped_anchor_rows = []\n"
            "for gene in ANCHOR_GENES:\n"
            "    gene_info = panel_manifest['genes'].get(gene, {})\n"
            "    variants_path, sequence_path, resolution_note = resolve_anchor_inputs(gene, gene_info, REPO_ROOT)\n"
            "    if variants_path is None or sequence_path is None:\n"
            "        dropped_anchor_rows.append({\n"
            "            'gene': gene,\n"
            "            'variants_found': variants_path is not None,\n"
            "            'sequence_found': sequence_path is not None,\n"
            "            'resolution_note': resolution_note,\n"
            "        })\n"
            "        continue\n"
            "    variants = json.loads(variants_path.read_text(encoding='utf-8'))\n"
            "    sequence_lines = [line.strip() for line in sequence_path.read_text(encoding='utf-8').splitlines() if line.strip()]\n"
            "    sequence = ''.join(line for line in sequence_lines if not line.startswith('>'))\n"
            "    anchor_variants[gene] = variants\n"
            "    anchor_sequences[gene] = sequence\n"
            "    anchor_gene_rows.append({\n"
            "        'gene': gene,\n"
            "        'variants_path': str(variants_path),\n"
            "        'sequence_path': str(sequence_path),\n"
            "        'n_total': len(variants),\n"
            "        'n_positive': int(sum(int(row['label']) for row in variants)),\n"
            "        'n_negative': int(len(variants) - sum(int(row['label']) for row in variants)),\n"
            "        'sequence_length': len(sequence),\n"
            "        'input_resolution': resolution_note,\n"
            "    })\n"
            "if not anchor_gene_rows:\n"
            "    raise FileNotFoundError('No anchor genes could be resolved from files tracked in this clone.')\n"
            "anchor_gene_table = pd.DataFrame(anchor_gene_rows)\n"
            "ANCHOR_GENES = tuple(anchor_gene_table['gene'].tolist())\n"
            "anchor_gene_table.to_csv(TABLES_DIR / 'anchor_gene_manifest_table.csv', index=False)\n"
            "if dropped_anchor_rows:\n"
            "    pd.DataFrame(dropped_anchor_rows).to_csv(TABLES_DIR / 'dropped_anchor_genes.csv', index=False)\n"
            "frozen_multigene_summary = pd.read_csv(resolved_artifacts['reject_multigene_summary'])\n"
            "frozen_multigene_summary = frozen_multigene_summary.loc[frozen_multigene_summary['gene'].isin(ANCHOR_GENES)].copy()\n"
            "block1_summary = pd.read_csv(resolved_artifacts['block1_reviewer_summary'])\n"
            "block1_summary = block1_summary.loc[block1_summary['gene'].isin([gene for gene in ANCHOR_GENES if gene in set(block1_summary['gene'])])].copy()\n"
            "block2_rows = pd.read_csv(resolved_artifacts['block2_rows'])\n"
            "display(anchor_gene_table)\n"
            "if dropped_anchor_rows:\n"
            "    display(pd.DataFrame(dropped_anchor_rows))\n"
            "done('Anchor gene inputs loaded.')\n"
        ),
        code_cell(
            "# Run the bounded live ESM2-35M sweep on the anchor genes\n"
            "light_model_rows = []\n"
            "for gene in ANCHOR_GENES:\n"
            "    gene_dir = ensure_dir(LIVE_SCORES_DIR / 'esm2_35m' / gene.lower())\n"
            "    score_rows = _ensure_gene_score_rows(\n"
            "        gene=gene,\n"
            "        sequence=anchor_sequences[gene],\n"
            "        variants=anchor_variants[gene],\n"
            "        model_name=LIGHT_MODEL_NAME,\n"
            "        output_dir=gene_dir,\n"
            "        window_radius=WINDOW_RADIUS,\n"
            "        checkpoint_every=max(1, CHECKPOINT_EVERY),\n"
            "        overwrite=OVERWRITE,\n"
            "    )\n"
            "    summary = _score_rows_summary(score_rows, PAIR_ALPHA)\n"
            "    light_model_rows.append({\n"
            "        'gene': gene,\n"
            "        'model_name': LIGHT_MODEL_NAME,\n"
            "        'model_label': 'ESM2-35M (live)',\n"
            "        'family_label': 'ESM2',\n"
            "        'baseline_label': 'll_proper',\n"
            "        'auc_baseline': summary['auc_ll_proper'],\n"
            "        'auc_covariance': summary['auc_frob_dist'],\n"
            "        'auc_pair_fixed_055': summary['auc_pair_fixed_055'],\n"
            "        'delta_pair_vs_baseline': summary['delta_pair_vs_ll'],\n"
            "        'source': 'live_esm2_35m',\n"
            "        'n_total': summary['n_total'],\n"
            "        'n_positive': summary['n_positive'],\n"
            "        'n_negative': summary['n_negative'],\n"
            "    })\n"
            "light_model_summary = pd.DataFrame(light_model_rows)\n"
            "light_model_summary.to_csv(TABLES_DIR / 'esm2_35m_live_summary.csv', index=False)\n"
            "display(light_model_summary)\n"
            "done('ESM2-35M live sweep finished.')\n"
        ),
        code_cell(
            "# Build the combined anchor-model summary from frozen and live evidence\n"
            "anchor_long_rows = []\n"
            "for _, row in frozen_multigene_summary.iterrows():\n"
            "    anchor_long_rows.append({\n"
            "        'gene': row['gene'],\n"
            "        'model_name': 'facebook/esm2_t30_150M_UR50D',\n"
            "        'model_label': 'ESM2-150M (frozen)',\n"
            "        'family_label': 'ESM2',\n"
            "        'baseline_label': 'll_proper',\n"
            "        'auc_baseline': safe_float(row['auc_ll_proper']),\n"
            "        'auc_covariance': safe_float(row['auc_frob_dist']),\n"
            "        'auc_pair_fixed_055': safe_float(row['auc_pair_fixed_055']),\n"
            "        'delta_pair_vs_baseline': safe_float(row['delta_pair_vs_ll']),\n"
            "        'source': 'frozen_reject_recovery_multigene',\n"
            "        'n_total': int(row['n_total']),\n"
            "        'n_positive': int(row['n_positive']),\n"
            "        'n_negative': int(row['n_negative']),\n"
            "    })\n"
            "if resolved_artifacts.get('reject_backbone_tp53_csv') is not None:\n"
            "    tp53_backbone_df = pd.read_csv(resolved_artifacts['reject_backbone_tp53_csv'])\n"
            "    tp53_650m = tp53_backbone_df.loc[tp53_backbone_df['model_name'].astype(str).eq('facebook/esm2_t33_650M_UR50D')]\n"
            "    if not tp53_650m.empty:\n"
            "        row = tp53_650m.iloc[0]\n"
            "        anchor_long_rows.append({\n"
            "            'gene': 'TP53',\n"
            "            'model_name': 'facebook/esm2_t33_650M_UR50D',\n"
            "            'model_label': 'ESM2-650M (frozen)',\n"
            "            'family_label': 'ESM2',\n"
            "            'baseline_label': 'll_proper',\n"
            "            'auc_baseline': safe_float(row['auc_ll_proper']),\n"
            "            'auc_covariance': safe_float(row['auc_frob_dist']),\n"
            "            'auc_pair_fixed_055': safe_float(row['auc_pair_fixed_055']),\n"
            "            'delta_pair_vs_baseline': safe_float(row['delta_pair_vs_ll']),\n"
            "            'source': 'frozen_tp53_backbone',\n"
            "            'n_total': int(row['n_total']),\n"
            "            'n_positive': int(anchor_gene_table.loc[anchor_gene_table['gene'].eq('TP53'), 'n_positive'].iloc[0]),\n"
            "            'n_negative': int(anchor_gene_table.loc[anchor_gene_table['gene'].eq('TP53'), 'n_negative'].iloc[0]),\n"
            "        })\n"
            "for _, row in block1_summary.iterrows():\n"
            "    anchor_long_rows.append({\n"
            "        'gene': row['gene'],\n"
            "        'model_name': 'facebook/esm1v_ensemble',\n"
            "        'model_label': 'ESM-1v ensemble (frozen)',\n"
            "        'family_label': 'ESM1v',\n"
            "        'baseline_label': 'esm1v_mean',\n"
            "        'auc_baseline': safe_float(row['auc_esm1v_mean']),\n"
            "        'auc_covariance': float('nan'),\n"
            "        'auc_pair_fixed_055': safe_float(row['auc_augmented_pair_fixed_055']),\n"
            "        'delta_pair_vs_baseline': safe_float(row['delta_augmented_vs_esm1v']),\n"
            "        'source': 'frozen_block1_esm1v',\n"
            "        'n_total': int(anchor_gene_table.loc[anchor_gene_table['gene'].eq(row['gene']), 'n_total'].iloc[0]),\n"
            "        'n_positive': int(anchor_gene_table.loc[anchor_gene_table['gene'].eq(row['gene']), 'n_positive'].iloc[0]),\n"
            "        'n_negative': int(anchor_gene_table.loc[anchor_gene_table['gene'].eq(row['gene']), 'n_negative'].iloc[0]),\n"
            "    })\n"
            "anchor_long_rows.extend(light_model_summary.to_dict(orient='records'))\n"
            "anchor_long = pd.DataFrame(anchor_long_rows)\n"
            "anchor_long = anchor_long.sort_values(['gene', 'model_label']).reset_index(drop=True)\n"
            "anchor_long.to_csv(TABLES_DIR / 'model_agnostic_anchor_long.csv', index=False)\n"
            "anchor_pivot = anchor_long.pivot_table(index='gene', columns='model_label', values='delta_pair_vs_baseline', aggfunc='first')\n"
            "anchor_pivot.to_csv(TABLES_DIR / 'model_agnostic_anchor_delta_pivot.csv')\n"
            "display(anchor_long)\n"
            "done('Combined anchor-model summary saved.')\n"
        ),
        code_cell(
            "# Cross-family ProtT5 subset audit on the Block 2 candidate/control pool\n"
            "block2_subset = block2_rows.loc[\n"
            "    block2_rows['validation_role'].astype(str).isin(['candidate_positive_existing_aug', 'candidate_positive_reference_extension', 'matched_positive_control'])\n"
            "].copy()\n"
            "block2_subset['audit_label'] = block2_subset['validation_role'].astype(str).str.startswith('candidate_positive').astype(int)\n"
            "block2_subset = block2_subset.sort_values(['gene', 'position', 'mut_aa']).reset_index(drop=True)\n"
            "block2_subset.to_csv(TABLES_DIR / 'block2_subset_for_cross_family_audit.csv', index=False)\n"
            "prott5_rows = []\n"
            "if RUN_PROTT5_SUBSET:\n"
            "    import torch\n"
            "    from transformers import T5EncoderModel, T5Tokenizer\n\n"
            "    def normalize_protein_sequence(sequence: str) -> str:\n"
            "        clean = re.sub(r'[UZOB]', 'X', sequence.upper())\n"
            "        return ' '.join(list(clean))\n\n"
            "    def select_t5_layers(hidden_states):\n"
            "        core = hidden_states[1:]\n"
            "        if PROTT5_LAYER_PROTOCOL == 'last':\n"
            "            return [core[-1]]\n"
            "        return list(core[-4:]) if len(core) >= 4 else list(core)\n\n"
            "    device = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
            "    torch_dtype = torch.float16 if device == 'cuda' else torch.float32\n"
            "    tokenizer = T5Tokenizer.from_pretrained(PROTT5_MODEL_NAME, do_lower_case=False, legacy=True)\n"
            "    model = T5EncoderModel.from_pretrained(PROTT5_MODEL_NAME, torch_dtype=torch_dtype, low_cpu_mem_usage=True).to(device).eval()\n\n"
            "    try:\n"
            "        wt_cache = {}\n"
            "        seq_cache = {}\n"
            "        for _, row in block2_subset.iterrows():\n"
            "            gene = str(row['gene']).upper()\n"
            "            position = int(row['position'])\n"
            "            wt_aa = str(row['wt_aa']).upper()\n"
            "            mut_aa = str(row['mut_aa']).upper()\n"
            "            if gene not in seq_cache:\n"
            "                if gene in anchor_sequences:\n"
            "                    seq_cache[gene] = anchor_sequences[gene]\n"
            "                elif gene in panel_manifest['genes']:\n"
            "                    seq_path = resolve_existing_path(panel_manifest['genes'][gene]['sequence_path'], REPO_ROOT)\n"
            "                    seq_lines = [line.strip() for line in seq_path.read_text(encoding='utf-8').splitlines() if line.strip()]\n"
            "                    seq_cache[gene] = ''.join(line for line in seq_lines if not line.startswith('>'))\n"
            "                else:\n"
            "                    raise KeyError(f'Missing sequence for gene {gene}')\n"
            "            sequence = seq_cache[gene]\n"
            "            if sequence[position].upper() != wt_aa:\n"
            "                raise ValueError(f'WT mismatch for {gene} {wt_aa}{position+1}{mut_aa}: found {sequence[position]}')\n"
            "            start = max(0, position - WINDOW_RADIUS)\n"
            "            end = min(len(sequence), position + WINDOW_RADIUS + 1)\n"
            "            local_sequence = sequence[start:end]\n"
            "            local_pos = position - start\n"
            "            wt_key = (gene, position)\n"
            "            if wt_key not in wt_cache:\n"
            "                wt_encoded = tokenizer(normalize_protein_sequence(local_sequence), return_tensors='pt')\n"
            "                wt_encoded = {key: value.to(device) for key, value in wt_encoded.items()}\n"
            "                with torch.inference_mode():\n"
            "                    wt_outputs = model(**wt_encoded, output_hidden_states=True)\n"
            "                wt_layers = []\n"
            "                for layer in select_t5_layers(wt_outputs.hidden_states):\n"
            "                    wt_layers.append(layer[0, :len(local_sequence), :].detach().cpu().float().numpy())\n"
            "                wt_hidden = np.stack(wt_layers, axis=0)\n"
            "                wt_cache[wt_key] = wt_hidden\n"
            "            wt_hidden = wt_cache[wt_key]\n"
            "            mutated_local = local_sequence[:local_pos] + mut_aa + local_sequence[local_pos + 1:]\n"
            "            mut_encoded = tokenizer(normalize_protein_sequence(mutated_local), return_tensors='pt')\n"
            "            mut_encoded = {key: value.to(device) for key, value in mut_encoded.items()}\n"
            "            with torch.inference_mode():\n"
            "                mut_outputs = model(**mut_encoded, output_hidden_states=True)\n"
            "            mut_layers = []\n"
            "            for layer in select_t5_layers(mut_outputs.hidden_states):\n"
            "                mut_layers.append(layer[0, :len(mutated_local), :].detach().cpu().float().numpy())\n"
            "            mut_hidden = np.stack(mut_layers, axis=0)\n"
            "            cov = covariance_features_dual(wt_hidden, mut_hidden)\n"
            "            token_shift = float(np.linalg.norm(mut_hidden[-1][local_pos] - wt_hidden[-1][local_pos]))\n"
            "            mean_shift = float(np.mean(np.linalg.norm(mut_hidden[-1] - wt_hidden[-1], axis=1)))\n"
            "            prott5_rows.append({\n"
            "                'gene': gene,\n"
            "                'name': row.get('name', f'{gene}_{wt_aa}{position+1}{mut_aa}'),\n"
            "                'position': position,\n"
            "                'wt_aa': wt_aa,\n"
            "                'mut_aa': mut_aa,\n"
            "                'validation_role': row['validation_role'],\n"
            "                'audit_label': int(row['audit_label']),\n"
            "                'frob_dist': float(cov['frob_dist']),\n"
            "                'trace_ratio': float(cov['trace_ratio']),\n"
            "                'sps_log': float(cov['sps_log']),\n"
            "                'mut_token_shift': token_shift,\n"
            "                'mean_token_shift': mean_shift,\n"
            "            })\n"
            "    finally:\n"
            "        del model\n"
            "        if torch.cuda.is_available():\n"
            "            torch.cuda.empty_cache()\n"
            "prott5_df = pd.DataFrame(prott5_rows)\n"
            "if not prott5_df.empty:\n"
            "    prott5_df['pair_fixed_055'] = pair_from_columns(prott5_df, 'frob_dist', 'mut_token_shift', PAIR_ALPHA)\n"
            "    prott5_df.to_csv(TABLES_DIR / 'prott5_subset_rows.csv', index=False)\n"
            "    prott5_summary = pd.DataFrame([\n"
            "        {'metric': 'n_total', 'value': int(len(prott5_df))},\n"
            "        {'metric': 'n_candidate', 'value': int(prott5_df['audit_label'].sum())},\n"
            "        {'metric': 'n_control', 'value': int(len(prott5_df) - prott5_df['audit_label'].sum())},\n"
            "        {'metric': 'auc_frob_dist', 'value': auc_safe(prott5_df['audit_label'], prott5_df['frob_dist'])},\n"
            "        {'metric': 'auc_mut_token_shift', 'value': auc_safe(prott5_df['audit_label'], prott5_df['mut_token_shift'])},\n"
            "        {'metric': 'auc_pair_fixed_055', 'value': auc_safe(prott5_df['audit_label'], prott5_df['pair_fixed_055'])},\n"
            "        {'metric': 'candidate_frob_mean', 'value': float(prott5_df.loc[prott5_df['audit_label'].eq(1), 'frob_dist'].mean())},\n"
            "        {'metric': 'control_frob_mean', 'value': float(prott5_df.loc[prott5_df['audit_label'].eq(0), 'frob_dist'].mean())},\n"
            "        {'metric': 'candidate_shift_mean', 'value': float(prott5_df.loc[prott5_df['audit_label'].eq(1), 'mut_token_shift'].mean())},\n"
            "        {'metric': 'control_shift_mean', 'value': float(prott5_df.loc[prott5_df['audit_label'].eq(0), 'mut_token_shift'].mean())},\n"
            "    ])\n"
            "else:\n"
            "    prott5_summary = pd.DataFrame([{'metric': 'status', 'value': 'not_run_or_empty'}])\n"
            "prott5_summary.to_csv(TABLES_DIR / 'prott5_subset_summary.csv', index=False)\n"
            "display(prott5_summary)\n"
            "done('ProtT5 subset audit finished.')\n"
        ),
        code_cell(
            "# Figures, reviewer-facing claim, manifests, and zip bundle\n"
            "plt.style.use('seaborn-v0_8-whitegrid')\n"
            "plot_df = anchor_long.dropna(subset=['delta_pair_vs_baseline']).copy()\n"
            "plot_df['gene_model'] = plot_df['gene'] + ' | ' + plot_df['model_label']\n"
            "plot_df = plot_df.sort_values('delta_pair_vs_baseline')\n"
            "fig, ax = plt.subplots(figsize=(10, max(4, 0.4 * len(plot_df))))\n"
            "colors = ['#0f766e' if value >= 0 else '#b91c1c' for value in plot_df['delta_pair_vs_baseline']]\n"
            "ax.barh(plot_df['gene_model'], plot_df['delta_pair_vs_baseline'], color=colors)\n"
            "ax.axvline(0.0, color='black', linewidth=1)\n"
            "ax.set_xlabel('Delta pair vs baseline')\n"
            "ax.set_title('Anchor-gene model audit')\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIGURES_DIR / 'anchor_gene_model_delta.png', dpi=200)\n"
            "plt.close(fig)\n"
            "pivot_auc = anchor_long.pivot_table(index='gene', columns='model_label', values='auc_pair_fixed_055', aggfunc='first')\n"
            "fig, ax = plt.subplots(figsize=(10, 4.5))\n"
            "im = ax.imshow(pivot_auc.fillna(np.nan).to_numpy(dtype=float), aspect='auto', cmap='YlGnBu')\n"
            "ax.set_xticks(range(len(pivot_auc.columns)))\n"
            "ax.set_xticklabels(list(pivot_auc.columns), rotation=20, ha='right')\n"
            "ax.set_yticks(range(len(pivot_auc.index)))\n"
            "ax.set_yticklabels(list(pivot_auc.index))\n"
            "ax.set_title('Pair AUC across anchor genes and models')\n"
            "fig.colorbar(im, ax=ax, label='AUC')\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIGURES_DIR / 'anchor_gene_pair_auc_heatmap.png', dpi=200)\n"
            "plt.close(fig)\n"
            "if not prott5_df.empty:\n"
            "    fig, ax = plt.subplots(figsize=(8, 5))\n"
            "    candidate_values = prott5_df.loc[prott5_df['audit_label'].eq(1), 'frob_dist'].to_numpy()\n"
            "    control_values = prott5_df.loc[prott5_df['audit_label'].eq(0), 'frob_dist'].to_numpy()\n"
            "    candidate_shift = prott5_df.loc[prott5_df['audit_label'].eq(1), 'mut_token_shift'].to_numpy()\n"
            "    control_shift = prott5_df.loc[prott5_df['audit_label'].eq(0), 'mut_token_shift'].to_numpy()\n"
            "    ax.boxplot([candidate_values, control_values, candidate_shift, control_shift], labels=['candidate frob', 'control frob', 'candidate shift', 'control shift'], patch_artist=True)\n"
            "    ax.set_title('ProtT5 cross-family subset audit')\n"
            "    ax.tick_params(axis='x', rotation=20)\n"
            "    fig.tight_layout()\n"
            "    fig.savefig(FIGURES_DIR / 'prott5_subset_audit.png', dpi=200)\n"
            "    plt.close(fig)\n"
            "block4_claim = 'family-bounded audit'\n"
            "claim_reason = 'Cross-family support was not strong enough to upgrade the claim.'\n"
            "if not prott5_df.empty:\n"
            "    auc_frob = float(prott5_summary.loc[prott5_summary['metric'].eq('auc_frob_dist'), 'value'].iloc[0])\n"
            "    auc_shift = float(prott5_summary.loc[prott5_summary['metric'].eq('auc_mut_token_shift'), 'value'].iloc[0])\n"
            "    candidate_frob = float(prott5_summary.loc[prott5_summary['metric'].eq('candidate_frob_mean'), 'value'].iloc[0])\n"
            "    control_frob = float(prott5_summary.loc[prott5_summary['metric'].eq('control_frob_mean'), 'value'].iloc[0])\n"
            "    if (not math.isnan(auc_frob)) and (auc_frob >= max(0.60, auc_shift + 0.03)) and (candidate_frob > control_frob):\n"
            "        block4_claim = 'model-agnostic covariance audit'\n"
            "        claim_reason = 'ProtT5 reproduces candidate-vs-control separation at the covariance channel, while the scalar token-shift baseline stays weaker.'\n"
            "summary = {\n"
            "    'notebook_slug': NOTEBOOK_SLUG,\n"
            "    'account_label': ACCOUNT_LABEL,\n"
            "    'run_at': RUN_AT,\n"
            "    'anchor_genes': list(ANCHOR_GENES),\n"
            "    'light_model_name': LIGHT_MODEL_NAME,\n"
            "    'prott5_model_name': PROTT5_MODEL_NAME,\n"
            "    'claim_status': block4_claim,\n"
            "    'claim_reason': claim_reason,\n"
            "    'n_anchor_rows': int(len(anchor_long)),\n"
            "    'positive_delta_rows': int((anchor_long['delta_pair_vs_baseline'].fillna(-999) > 0).sum()),\n"
            "}\n"
            "(MANIFESTS_DIR / 'block4_summary.json').write_text(json.dumps(summary, indent=2), encoding='utf-8')\n"
            "artifact_summary = {\n"
            "    'tables_dir': str(TABLES_DIR),\n"
            "    'figures_dir': str(FIGURES_DIR),\n"
            "    'text_dir': str(TEXT_DIR),\n"
            "    'zip_path': str(ZIP_PATH),\n"
            "    'root_zip_copy': str(ROOT_ZIP_COPY),\n"
            "}\n"
            "(MANIFESTS_DIR / 'artifact_summary.json').write_text(json.dumps(artifact_summary, indent=2), encoding='utf-8')\n"
            "summary_md = '\\n'.join([\n"
            "    '# Block 4 summary',\n"
            "    '',\n"
            "    f'- Claim status: `{block4_claim}`',\n"
            "    f'- Claim reason: {claim_reason}',\n"
            "    f'- Anchor genes: `{\", \".join(ANCHOR_GENES)}`',\n"
            "    f'- Light live model: `{LIGHT_MODEL_NAME}`',\n"
            "    f'- Cross-family subset model: `{PROTT5_MODEL_NAME}`',\n"
            "    f'- Anchor evidence rows: `{int(len(anchor_long))}`',\n"
            "])\n"
            "(TEXT_DIR / 'block4_summary.md').write_text(summary_md + '\\n', encoding='utf-8')\n"
            "if ZIP_PATH.exists():\n"
            "    ZIP_PATH.unlink()\n"
            "with zipfile.ZipFile(ZIP_PATH, 'w', compression=zipfile.ZIP_DEFLATED) as bundle:\n"
            "    for path in sorted(RESULTS_ROOT.rglob('*')):\n"
            "        if path.is_file():\n"
            "            bundle.write(path, arcname=path.relative_to(RESULTS_ROOT))\n"
            "shutil.copy2(ZIP_PATH, ROOT_ZIP_COPY)\n"
            "print(json.dumps(summary, indent=2))\n"
            "print({'zip_path': str(ZIP_PATH), 'root_zip_copy': str(ROOT_ZIP_COPY)})\n"
            "done('Block 4 bundle is ready for download.')\n"
        ),
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.12",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return notebook


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    notebook_path = repo_root / "New Notebooks" / "03_block4_model_agnostic_plms_h100_v2.ipynb"
    notebook_path.parent.mkdir(parents=True, exist_ok=True)
    notebook = build_notebook()
    notebook_path.write_text(json.dumps(notebook, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {notebook_path}")


if __name__ == "__main__":
    main()
